[package]
name = "rust-in-c"
version = "0.1.0"
authors = ["administrator"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[lib]
crate-type = ["cdylib"]
name = "integers"